In [1]:
import pandas as pd

In [ ]:
## http://www.scielo.br/scieloOrg/php/articleXML.php?pid=S1806-11172013000300019&lang=en

In [ ]:
wget 'http://www.scielo.br/scieloOrg/php/articleXML.php?pid=S1806-11172013000300019&lang=en'

In [2]:
import wget
url = 'http://www.scielo.br/scieloOrg/php/articleXML.php?pid=S1806-11172013000300019&lang=en'
filename = wget.download(url)

ModuleNotFoundError: No module named 'wget'

In [2]:
import requests
import pandas as pd
import xml.etree.ElementTree as et

def get_poll_xml(poll_id):
    url="http://charts.realclearpolitics.com/charts/{}.xml".format(poll_id)
    return requests.get(url).content

def rcp_poll_data(xml):

    tree = et.fromstring(xml)

    dates = []; graphlist1 = []; graphlist2 = []

    g1title = tree.find("./graphs/graph[@gid='1']").get('title')
    g2title = tree.find("./graphs/graph[@gid='2']").get('title')

    for s, g1, g2 in zip(tree.iterfind("./series/value"),
                         tree.iterfind("./graphs/graph[@gid='1']/value"),
                         tree.iterfind("./graphs/graph[@gid='2']/value")):
        dates.append(s.text)
        graphlist1.append(g1.text)
        graphlist2.append(g2.text)

    return pd.DataFrame({'Date':pd.to_datetime(dates, errors="ignore"),
                         g1title: graphlist1,
                         g2title: graphlist2})

poll_id = 1044
xml_str = get_poll_xml(poll_id)
df = rcp_poll_data(xml_str)
df

     Approve       Date Disapprove
0       63.3 2009-01-27       20.0
1       63.3 2009-01-28       20.0
2       63.5 2009-01-29       19.3
3       63.5 2009-01-30       19.3
4       61.8 2009-01-31       19.4
5       61.8 2009-02-01       19.4
6       61.8 2009-02-02       19.4
7       61.8 2009-02-03       19.4
8       61.8 2009-02-04       19.4
9       61.8 2009-02-05       19.4
10      61.6 2009-02-06       21.4
11      61.6 2009-02-07       21.4
12      61.6 2009-02-08       21.4
13      65.4 2009-02-09       22.6
14      65.4 2009-02-10       22.6
15      64.2 2009-02-11       23.3
16      64.2 2009-02-12       23.3
17      64.2 2009-02-13       23.3
18      64.8 2009-02-14       25.4
19      65.5 2009-02-15       25.5
20      65.5 2009-02-16       25.5
21      65.5 2009-02-17       25.5
22      65.1 2009-02-18       25.9
23      62.3 2009-02-19       28.5
24      63.2 2009-02-20       28.6
25      63.2 2009-02-21       28.6
26      63.2 2009-02-22       28.6
27      63.0 2009-02-23       27.8
28      62.5 2009-02-24       27.8
29      62.5 2009-02-25       27.8
...      ...        ...        ...
1801    42.6 2014-01-02       53.4
1802    42.4 2014-01-03       53.6
1803    42.4 2014-01-04       53.8
1804    42.3 2014-01-05       53.8
1805    42.4 2014-01-06       53.7
1806    42.8 2014-01-07       53.7
1807    42.4 2014-01-08       53.6
1808    42.1 2014-01-09       53.1
1809    42.0 2014-01-10       53.1
1810    42.0 2014-01-11       53.3
1811    42.1 2014-01-12       53.4
1812    42.0 2014-01-13       53.4
1813    41.9 2014-01-14       53.6
1814    42.1 2014-01-15       53.3
1815    42.3 2014-01-16       53.4
1816    42.4 2014-01-17       52.8
1817    42.2 2014-01-18       53.0
1818    42.0 2014-01-19       53.2
1819    42.5 2014-01-20       52.2
1820    42.8 2014-01-21       51.8
1821    42.8 2014-01-22       51.9
1822    43.2 2014-01-23       51.6
1823    43.2 2014-01-24       51.7
1824    None 2014-01-25       None
1825    None 2014-01-26       None
1826    None 2014-01-27       None
1827    None 2014-01-28       None
1828    None 2014-01-29       None
1829    None 2014-01-30       None
1830    None 2014-01-31       None

[1831 rows x 3 columns]

In [8]:
import xml.etree.ElementTree as ET
from lxml import etree
import pandas as pd

xml_data = 'www.scielo.br/scieloOrg/php/articleXML.php?pid=S1806-11172013000300019&lang=en'

def xml2df(xml_data):
    tree = ET.parse(xml_data)
    root = tree.getroot()
    all_records = []
    headers = []
    for i, child in enumerate(root):
        record = []
        for subchild in child:
            record.append(subchild.text)
            if subchild.tag not in headers:
                headers.append(subchild.tag)
        all_records.append(record)
    return pd.DataFrame(all_records, columns=headers)

df = xml2df(xml_data)

FileNotFoundError: [Errno 2] No such file or directory: 'www.scielo.br/scieloOrg/php/articleXML.php?pid=S1806-11172013000300019&lang=en'